export default {
    AUTH_SWITCH_ROUTE: "AUTH_SWITCH_ROUTE",

    HANDLE_LOADER: "HANDLE_LOADER",

    SET_TAB_TYPE: "SET_TAB_TYPE",

    SIGNUP_LOADING: "SIGNUP_LOADING",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAIL: "SIGNUP_FAIL",

    LOGIN_LOADING: "LOGIN_LOADING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",

    LOGOUT: "LOGOUT",
    SET_MEMBER_OR_SELLER: "SET_MEMBER_OR_SELLER",

    RESET_PASSWORD_LOADING: "RESET_PASSWORD_LOADING",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAIL: "RESET_PASSWORD_FAIL",

    FORGOT_PASSWORD_LOADING: "FORGOT_PASSWORD_LOADING",
    FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",

    GET_USER_LOADING: "GET_USER_LOADING",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAIL: "GET_USER_FAIL",

    UPDATE_USER_LOADING: "UPDATE_USER_LOADING",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAIL: "UPDATE_USER_FAIL",

    CHANGE_PASSWORD_LOADING: "CHANGE_PASSWORD_LOADING",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_FAIL: "CHANGE_PASSWORD_FAIL",

    VERIFY_OTP_LOADING: "VERIFY_OTP_LOADING",
    VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
    VERIFY_OTP_FAIL: "VERIFY_OTP_FAIL",

    GET_FLASH_PRODUCT_LOADING: "GET_FLASH_PRODUCT_LOADING",
    GET_FLASH_PRODUCT_SUCCESS: "GET_FLASH_PRODUCT_SUCCESS",
    GET_FLASH_PRODUCT_FAIL: "GET_FLASH_PRODUCT_FAIL",

    GET_BEST_SELLING_PRODUCT_LOADING: "GET_BEST_SELLING_PRODUCT_LOADING",
    GET_BEST_SELLING_PRODUCT_SUCCESS: "GET_BEST_SELLING_PRODUCT_SUCCESS",
    GET_BEST_SELLING_PRODUCT_FAIL: "GET_BEST_SELLING_PRODUCT_FAIL",

    GET_SEASON_TOP_PRODUCT_LOADING: "GET_SEASON_TOP_PRODUCT_LOADING",
    GET_SEASON_TOP_PRODUCT_SUCCESS: "GET_SEASON_TOP_PRODUCT_SUCCESS",
    GET_SEASON_TOP_PRODUCT_FAIL: "GET_SEASON_TOP_PRODUCT_FAIL",

    GET_TOP_PICK_ON_PRODUCT_LOADING: "GET_TOP_PICK_ON_PRODUCT_LOADING",
    GET_TOP_PICK_ON_PRODUCT_SUCCESS: "GET_TOP_PICK_ON_PRODUCT_SUCCESS",
    GET_TOP_PICK_ON_PRODUCT_FAIL: "GET_TOP_PICK_ON_PRODUCT_FAIL",

    GET_TRENDING_PRODUCT_LOADING: "GET_TRENDING_PRODUCT_LOADING",
    GET_TRENDING_PRODUCT_SUCCESS: "GET_TRENDING_PRODUCT_SUCCESS",
    GET_TRENDING_PRODUCT_FAIL: "GET_TRENDING_PRODUCT_FAIL",

    GET_CATEGORY_LOADING: "GET_CATEGORY_LOADING",
    GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
    GET_CATEGORY_FAIL: "GET_CATEGORY_FAIL",

    SOCIAL_MEDIA_LOGIN: "SOCIAL_MEDIA_LOGIN",
    SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
    SET_PRODUCT_DETAILS: "SET_PRODUCT_DETAILS",

    ADD_CART_LOADING: "ADD_CART_LOADING",
    ADD_CART_SUCCESS: "ADD_CART_SUCCESS",
    ADD_CART_FAIL: "ADD_CART_FAIL",

    INCREASE_IN_CART_LOADING: "INCREASE_IN_CART_LOADING",
    INCREASE_IN_CART_SUCCESS: "INCREASE_IN_CART_SUCCESS",
    INCREASE_IN_CART_FAIL: "INCREASE_IN_CART_FAIL",

    DECREASE_IN_CART_LOADING: "DECREASE_IN_CART_LOADING",
    DECREASE_IN_CART_SUCCESS: "DECREASE_IN_CART_SUCCESS",
    DECREASE_IN_CART_FAIL: "DECREASE_IN_CART_FAIL",

    REMOVE_FROM_CART_LOADING: "REMOVE_FROM_CART_LOADING",
    REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
    REMOVE_FROM_CART_FAIL: "REMOVE_FROM_CART_FAIL",

    GET_CART_LIST_LOADING: "GET_CART_LIST_LOADING",
    GET_CART_LIST_SUCCESS: "GET_CART_LIST_SUCCESS",
    GET_CART_LIST_FAIL: "GET_CART_LIST_FAIL",

    ADD_TO_WISHLIST_LOADING: "ADD_TO_WISHLIST_LOADING",
    ADD_TO_WISHLIST_SUCCESS: "ADD_TO_WISHLIST_SUCCESS",
    ADD_TO_WISHLIST_FAIL: "ADD_TO_WISHLIST_FAIL",

    REMOVE_FROM_WISHLIST_LOADING: "REMOVE_FROM_WISHLIST_LOADING",
    REMOVE_FROM_WISHLIST_SUCCESS: "REMOVE_FROM_WISHLIST_SUCCESS",
    REMOVE_FROM_WISHLIST_FAIL: "REMOVE_FROM_WISHLIST_FAIL",

    GET_WISHLIST_LOADING: "GET_WISHLIST_LOADING",
    GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",
    GET_WISHLIST_FAIL: "GET_WISHLIST_FAIL",

    GET_COUNRTY_LOADING: "GET_COUNRTY_LOADING",
    GET_COUNRTY_SUCCESS: "GET_COUNRTY_SUCCESS",
    GET_COUNRTY_FAIL: "GET_COUNRTY_FAIL",

    GET_STATE_LOADING: "GET_STATE_LOADING",
    GET_STATE_SUCCESS: "GET_STATE_SUCCESS",
    GET_STATE_FAIL: "GET_STATE_FAIL",

    GET_CITY_LOADING: "GET_CITY_LOADING",
    GET_CITY_SUCCESS: "GET_CITY_SUCCESS",
    GET_CITY_FAIL: "GET_CITY_FAIL",

    PLACE_ORDER_SUCCESS: "PLACE_ORDER_SUCCESS",
    PLACE_ORDER_FAIL: "PLACE_ORDER_FAIL",

    SAVE_ADDRESS: "SAVE_ADDRESS",

    ADD_NEW_ADDRESS_SUCCESS: "ADD_NEW_ADDRESS_SUCCESS",
    ADD_NEW_ADDRESS_FAIL: "ADD_NEW_ADDRESS_FAIL",

    CHECK_IF_PIN_EXIST_SUCCESS: "CHECK_IF_PIN_EXIST_SUCCESS",
    CHECK_IF_PIN_EXIST_FAIL: "CHECK_IF_PIN_EXIST_FAIL",
    UNSET_PIN_DATA: "UNSET_PIN_DATA",

    CHECK_IF_EMAIL_EXIST_SUCCESS: "CHECK_IF_EMAIL_EXIST_SUCCESS",
    CHECK_IF_EMAIL_EXIST_FAIL: "CHECK_IF_EMAIL_EXIST_FAIL",
    CLEAR_EMAIL_EXIST: "CLEAR_EMAIL_EXIST",

    ORDER_SUMMARY_SUCCESS: "ORDER_SUMMARY_SUCCESS",
    ORDER_SUMMARY_FAIL: "ORDER_SUMMARY_FAIL",

    ORDER_DETAIL_SUCCESS: "ORDER_DETAIL_SUCCESS",
    ORDER_DETAIL_FAIL: "ORDER_DETAIL_FAIL",

    CANCEL_ORDER_BY_USER_SUCCESS: "CANCEL_ORDER_BY_USER_SUCCESS",
    CANCEL_ORDER_BY_USER_FAIL: "CANCEL_ORDER_BY_USER_FAIL",

    SET_SOCIAL_MEDIA_DATA: "SET_SOCIAL_MEDIA_DATA",
    SET_CURRENCY_TYPE: "SET_CURRENCY_TYPE",
    TODAY_CURRENCY_RATE: "TODAY_CURRENCY_RATE",

    GET_PRODUCT_BY_CATEGORYID_LOADING: "GET_PRODUCT_BY_CATEGORYID_LOADING",
    GET_PRODUCT_BY_CATEGORYID_SUCCESS: "GET_PRODUCT_BY_CATEGORYID_SUCCESS",
    GET_PRODUCT_BY_CATEGORYID_FAIL: "GET_PRODUCT_BY_CATEGORYID_FAIL",

    GET_PRODUCT_BY_KEYWORD_LOADING: "GET_PRODUCT_BY_KEYWORD_LOADING",
    GET_PRODUCT_BY_KEYWORD_SUCCESS: "GET_PRODUCT_BY_KEYWORD_SUCCESS",
    GET_PRODUCT_BY_KEYWORD_FAIL: "GET_PRODUCT_BY_KEYWORD_FAIL",

    GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
    GET_ALL_PRODUCT_FAIL: "GET_ALL_PRODUCT_FAIL",

    CLEAR_SEARCH_PRODUCT: "CLEAR_SEARCH_PRODUCT",

    FILTER_CURRENCY: "FILTER_CURRENCY",
    FILTER_COUNTRY: "FILTER_COUNTRY",
    FILTER_STATE: "FILTER_STATE",
    FILTER_CITY: "FILTER_CITY",

    WALLET_HISTORY_LOADING: "WALLET_HISTORY_LOADING",
    WALLET_HISTORY_SUCCESS: "WALLET_HISTORY_SUCCESS",
    WALLET_HISTORY_FAIL: "WALLET_HISTORY_FAIL",

    SET_SELECTED_WALLET_DETAILS: "SET_SELECTED_WALLET_DETAILS",

    TRANSFER_FUND_LOADING: "TRANSFER_FUND_LOADING",
    TRANSFER_FUND_SUCCESS: "TRANSFER_FUND_SUCCESS",
    TRANSFER_FUND_FAIL: "TRANSFER_FUND_FAIL",

    GET_SUPPORT_HISTORY_LOADING: "GET_SUPPORT_HISTORY_LOADING",
    GET_SUPPORT_HISTORY_SUCCESS: "GET_SUPPORT_HISTORY_SUCCESS",
    GET_SUPPORT_HISTORY_FAIL: "GET_SUPPORT_HISTORY_FAIL",

    RAISE_COMPLAIN_TICKET_LOADING: "RAISE_COMPLAIN_TICKET_LOADING",
    RAISE_COMPLAIN_TICKET_SUCCESS: "RAISE_COMPLAIN_TICKET_SUCCESS",
    RAISE_COMPLAIN_TICKET_FAIL: "RAISE_COMPLAIN_TICKET_FAIL",

    GET_TICKET_BY_TICKET_ID_LOADING: "GET_TICKET_BY_TICKET_ID_LOADING",
    GET_TICKET_BY_TICKET_ID_SUCCESS: "GET_TICKET_BY_TICKET_ID_SUCCESS",
    GET_TICKET_BY_TICKET_ID_FAIL: "GET_TICKET_BY_TICKET_ID_FAIL",

    GET_ISSUE_LIST_LOADING: "GET_ISSUE_LIST_LOADING",
    GET_ISSUE_LIST_SUCCESS: "GET_ISSUE_LIST_SUCCESS",
    GET_ISSUE_LIST_FAIL: "GET_ISSUE_LIST_FAIL",

    REPLY_ON_TICKET_SUCCESS: "REPLY_ON_TICKET_SUCCESS",
    REPLY_ON_TICKET_FAIL: "REPLY_ON_TICKET_FAIL",

    SET_TICKET_DETAILS: "SET_TICKET_DETAILS",

    GET_NETWORK_SUCCESS: "GET_NETWORK_SUCCESS",
    GET_NETWORK_FAIL: "GET_NETWORK_FAIL",

    PRODUCT_DETAILS_BY_ID_SUCCESS: "PRODUCT_DETAILS_BY_ID_SUCCESS",
    PRODUCT_DETAILS_BY_ID_FAIL: "PRODUCT_DETAILS_BY_ID_FAIL",

    //SOCIAL MEDIA
    GET_FEELING_ACTIVITY_SUCCESS: "GET_FEELING_ACTIVITY_SUCCESS",
    GET_FEELING_ACTIVITY_FAIL: "GET_FEELING_ACTIVITY_FAIL",

    GET_USER_BY_TAG_SUCCESS: "GET_USER_BY_TAG_SUCCESS",
    GET_USER_BY_TAG_FAIL: "GET_USER_BY_TAG_FAIL",

    CREATE_NEW_POST_SUCCESS: "CREATE_NEW_POST_SUCCESS",
    CREATE_NEW_POST_FAIL: "CREATE_NEW_POST_FAIL",

    GET_POST_LIST_BY_USER_SUCCESS: "GET_POST_LIST_BY_USER_SUCCESS",
    GET_POST_LIST_BY_USER_FAIL: "GET_POST_LIST_BY_USER_FAIL",

    LIKE_ON_POST_SUCCESS: "LIKE_ON_POST_SUCCESS",
    LIKE_ON_POST_FAIL: "LIKE_ON_POST_FAIL",

    REMOVE_LIKE_FROM_POST_SUCCESS: "REMOVE_LIKE_FROM_POST_SUCCESS",
    REMOVE_LIKE_FROM_POST_FAIL: "REMOVE_LIKE_FROM_POST_FAIL",

    COMMENT_ON_POST_SUCCESS: "COMMENT_ON_POST_SUCCESS",
    COMMENT_ON_POST_FAIL: "COMMENT_ON_POST_FAIL",

    COMMENT_LIST_BY_POST_SUCCESS: "COMMENT_LIST_BY_POST_SUCCESS",
    COMMENT_LIST_BY_POST_FAIL: "COMMENT_LIST_BY_POST_FAIL",

    SHARE_POST_SUCCESS: "SHARE_POST_SUCCESS",
    SHARE_POST_FAIL: "SHARE_POST_FAIL",

    GET_PARTICULAR_POST_SUCCESS: "GET_PARTICULAR_POST_SUCCESS",
    GET_PARTICULAR_POST_FAIL: "GET_PARTICULAR_POST_FAIL",

    EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
    EDIT_POST_FAIL: "EDIT_POST_FAIL",

    DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
    DELETE_POST_FAIL: "DELETE_POST_FAIL",

    SEND_FOLLOW_REQUEST_SUCCESS: "SEND_FOLLOW_REQUEST_SUCCESS",
    SEND_FOLLOW_REQUEST_FAIL: "SEND_FOLLOW_REQUEST_FAIL",

    ACCEPT_FOLLOW_REQUEST_SUCCESS: "ACCEPT_FOLLOW_REQUEST_SUCCESS",
    ACCEPT_FOLLOW_REQUEST_FAIL: "ACCEPT_FOLLOW_REQUEST_FAIL",

    GET_FOLLOWS_LIST_BY_USER_SUCCESS: "GET_FOLLOWS_LIST_BY_USER_SUCCESS",
    GET_FOLLOWS_LIST_BY_USER_FAIL: "GET_FOLLOWS_LIST_BY_USER_FAIL",

    SET_SELECTED_FFELING: "SET_SELECTED_FFELING",
    SET_TAGGED_PEOPLE: "SET_TAGGED_PEOPLE",
    SET_SEARCHED_TAGGED_PEOPLE: "SET_SEARCHED_TAGGED_PEOPLE",

    UPDATE_PROFILE_PIC_SUCCESS: "UPDATE_PROFILE_PIC_SUCCESS",
    UPDATE_PROFILE_PIC_FAIL: "UPDATE_PROFILE_PIC_FAIL",

    UPDATE_COVER_PIC_SUCCESS: "UPDATE_COVER_PIC_SUCCESS",
    UPDATE_COVER_PIC_FAIL: "UPDATE_COVER_PIC_FAIL",

    UPLOAD_POST_IMAGE_SUCCESS: "UPLOAD_POST_IMAGE_SUCCESS",
    UPLOAD_POST_IMAGE_FAIL: "UPLOAD_POST_IMAGE_FAIL",

    GET_USER_IMAGE_SUCCESS: "GET_USER_IMAGE_SUCCESS",
    GET_USER_IMAGE_FAIL: "GET_USER_IMAGE_FAIL",

    GET_FRIEND_SUGGESTION_LIST_SUCCESS: "GET_FRIEND_SUGGESTION_LIST_SUCCESS",
    GET_FRIEND_SUGGESTION_LIST_FAIL: "GET_FRIEND_SUGGESTION_LIST_FAIL",

    CANCEL_FRIEND_REQUEST_SUCCESS: "CANCEL_FRIEND_REQUEST_SUCCESS",
    CANCEL_FRIEND_REQUEST_FAIL: "CANCEL_FRIEND_REQUEST_FAIL",

    FETCH_USER_PROFILE_DATA_SUCCESS: "FETCH_USER_PROFILE_DATA_SUCCESS",
    FETCH_USER_PROFILE_DATA_FAIL: "FETCH_USER_PROFILE_DATA_FAIL",

    CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
    CREATE_GROUP_FAIL: "CREATE_GROUP_FAIL",

    GET_GROUP_LIST_SUCCESS: "GET_GROUP_LIST_SUCCESS",
    GET_GROUP_LIST_FAIL: "GET_GROUP_LIST_FAIL",

    UPLOAD_GROUP_IMAGES_SUCCESS: "UPLOAD_GROUP_IMAGES_SUCCESS",
    UPLOAD_GROUP_IMAGES_FAIL: "UPLOAD_GROUP_IMAGES_FAIL",

    UPLOAD_GROUP_COVER_SUCCESS: "UPLOAD_GROUP_COVER_SUCCESS",
    UPLOAD_GROUP_COVER_FAIL: "UPLOAD_GROUP_COVER_FAIL",

    CREATE_GROUP_POST_SUCCESS: "CREATE_GROUP_POST_SUCCESS",
    CREATE_GROUP_POST_FAIL: "CREATE_GROUP_POST_FAIL",

    FETCH_GROUP_POST_LIST_BY_USER_SUCCESS: "FETCH_GROUP_POST_LIST_BY_USER_SUCCESS",
    FETCH_GROUP_POST_LIST_BY_USER_FAIL: "FETCH_GROUP_POST_LIST_BY_USER_FAIL",

    SET_SELECTED_GROUP: "SET_SELECTED_GROUP",

    ADD_COMMENT_ON_GROUP_POST_SUCCESS: "ADD_COMMENT_ON_GROUP_POST_SUCCESS",
    ADD_COMMENT_ON_GROUP_POST_FAIL: "ADD_COMMENT_ON_GROUP_POST_FAIL",

    GET_COMMENT_LIST_ON_GROUP_POST_SUCCESS: "GET_COMMENT_LIST_ON_GROUP_POST_SUCCESS",
    GET_COMMENT_LIST_ON_GROUP_POST_FAIL: "GET_COMMENT_LIST_ON_GROUP_POST_FAIL",

    JOIN_GROUP_SUCCESS: "JOIN_GROUP_SUCCESS",
    JOIN_GROUP_FAIL: "JOIN_GROUP_FAIL",
    SET_SEARCHED_GROUP: "SET_SEARCHED_GROUP",

    //PAGES
    CREATE_NEW_PAGE_SUCCESS: "CREATE_NEW_PAGE_SUCCESS",
    CREATE_NEW_PAGE_FAIL: "CREATE_NEW_PAGE_FAIL",

    FETCH_ALL_PAGES_BY_USER_SUCCESS: "FETCH_ALL_PAGES_BY_USER_SUCCESS",
    FETCH_ALL_PAGES_BY_USER_FAIL: "FETCH_ALL_PAGES_BY_USER_FAIL",

    CREATE_POST_FOR_PAGE_SUCCESS: "CREATE_POST_FOR_PAGE_SUCCESS",
    CREATE_POST_FOR_PAGE_FAIL: "CREATE_POST_FOR_PAGE_FAIL",

    COMMENT_ON_PAGE_POST_SUCCESS: "COMMENT_ON_PAGE_POST_SUCCESS",
    COMMENT_ON_PAGE_POST_FAIL: "COMMENT_ON_PAGE_POST_FAIL",

    LIKE_A_PAGE_SUCCESS: "LIKE_A_PAGE_SUCCESS",
    LIKE_A_PAGE_FAIL: "LIKE_A_PAGE_FAIL",

    SEND_INVITE_TO_LIKE_PAGE_SUCCESS: "SEND_INVITE_TO_LIKE_PAGE_SUCCESS",
    SEND_INVITE_TO_LIKE_PAGE_FAIL: "SEND_INVITE_TO_LIKE_PAGE_FAIL",

    ACCEPT_INVITATION_TO_LIKE_PAGE_SUCCESS: "ACCEPT_INVITATION_TO_LIKE_PAGE_SUCCESS",
    ACCEPT_INVITATION_TO_LIKE_PAGE_FAIL: "ACCEPT_INVITATION_TO_LIKE_PAGE_FAIL",

    FETCH_LIKED_AND_PENDING_PAGE_SUCCESS: "FETCH_LIKED_AND_PENDING_PAGE_SUCCESS",
    FETCH_LIKED_AND_PENDING_PAGE_FAIL: "FETCH_LIKED_AND_PENDING_PAGE_FAIL",

    UPLOAD_PAGE_IMAGES_SUCCESS: "UPLOAD_PAGE_IMAGES_SUCCESS",
    UPLOAD_PAGE_IMAGES_FAIL: "UPLOAD_PAGE_IMAGES_FAIL",

    UPLOAD_PAGE_COVER_SUCCESS: "UPLOAD_PAGE_COVER_SUCCESS",
    UPLOAD_PAGE_COVER_FAIL: "UPLOAD_PAGE_COVER_FAIL",



}